### PR TITLE
Note logging/ES changes in README

### LINKED ISSUE #5: Update README to reflect removal of Elasticsearch logging

### PR DESCRIPTION
**Pull request by tylerjl**
Resolves #5

### CODE REVIEW

**Review by olksdr — APPROVED** [review]
LGTM!

I knew I forgot to update something at the end. @tylerjl thanks for taking care of this!

**Review by olksdr — CHANGES_REQUESTED** [review]
Sorry, not quite done yet,

you will need to remove the  `--es` mentions from the `Usage` line as well 
```
Usage: hipio DOMAIN [PORT] [--es URL] [-a RECORD] [--ns RECORD]
```

**Comment by tylerjl** [comment]
@olksdr I actually think you took care of that :smile: in [your commit](https://github.com/elastic/hipio/commit/dd0d4a39f375f3c6aa643ee11b81afb9c53bc4b4#diff-63e7d2cbf23880a9c902c91fa34f6043L73-L79) removing the argument took care of any mention appearing the CLI usage text. Running the executable from this branch doesn't include that ES mention in the usage text for me.

```
$ stack exec -- hipio
Missing: DOMAIN --soa-email EMAIL

Usage: hipio DOMAIN [PORT] [-a RECORD] [--ns RECORD] --soa-email EMAIL
  hipio maps <anything>.<IP Address>.<domain> to the corresponding <IP Address>,
  e.g. 127.0.0.1.<domain> maps to 127.0.0.1
```

**Comment by olksdr** [comment]
> @olksdr I actually think you took care of that 😄 in [your commit](https://github.com/elastic/hipio/commit/dd0d4a39f375f3c6aa643ee11b81afb9c53bc4b4#diff-63e7d2cbf23880a9c902c91fa34f6043L73-L79) removing the argument took care of any mention appearing the CLI usage text. Running the executable from this branch doesn't include that ES mention in the usage text for me.

That's true 😄 But I was talking about the README where it's still mentioned on [line 12](https://github.com/elastic/hipio/pull/6/files#diff-04c6e90faac2675aa89e2176d2eec7d8R12) 
Sorry if I wasn't clear

**Comment by tylerjl** [comment]
Ah, sorry about missing that! b5633b7

**Review by olksdr — APPROVED** [review]
I think we good to go 👍

**Pull request merged**
